stages:
  - build
  - test

build:
  tags:
    - dealii
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja debug
    - ninja -j1

test:
  tags:
    - dealii
  stage: test
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja debug
    - ninja -j1
    - ./wavepi_test
  when: manual
