cache:
  key: ${CI_JOB_NAME}
  paths:
    - build

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DWAVEPI_WITH_MPI=ON
    - make -j2
    - mkdir -p ../dist
    - for f in $(find . -name "libwavepi*.so"); do cp $f ../dist; done
    - for f in wavepi*; do cp $f ../dist; done
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  tags:
    - docker
  image: git.thiesgerken.de:5005/thies/wavepi/dealii:d68d619

test:
  stage: test
  dependencies:
    - build
  script:
    - cd dist
    - ./wavepi_test
  when: manual
  tags:
    - docker
  image: git.thiesgerken.de:5005/thies/wavepi/dealii:d68d619
