stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make

test:
  stage: test
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make
    - ./wavepi_test
  when: manual
